# -*- mode: ruby -*-
# vi: set ft=ruby :

# -*- mode: ruby -*-
# vi: set ft=ruby :
  
Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    config.vm.network "private_network", ip: "192.168.56.102"
    config.vm.hostname = "worker2.xtl"
  
    config.vm.provider "virtualbox" do |vb|
       vb.name = "worker2.xtl"
       vb.cpus = 1
       vb.memory = "1024"
    end
     
    config.vm.provision "shell", path: "./../install-docker-kube.sh"
  
    config.vm.provision "shell", inline: <<-SHELL
    
      echo "root password"
      echo "123" | passwd --stdin root
      sed -i 's/^PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
      systemctl reload sshd
      
  
  cat >>/etc/hosts<<EOF
  192.168.56.100 master.xtl
  192.168.56.101 worker1.xtl
  192.168.56.102 worker2.xtl
  EOF
  
  
    SHELL
  end