apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv1
  labels:
    name: pv1
spec:
  storageClassName: mystorageclass
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce # read-write by a single node
  hostPath: # hostPath PV type - for single node testing only; WILL NOT WORK in a multi-node cluster; consider using local volume instead
    path: "/v1" # folder in node
