apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc1
  labels:
    name: pvc1
spec:
  storageClassName: mystorageclass # find PV with correspond storage class name
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 150Mi
